name: Documentation generation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x'
        channel: 'stable'

    - run: dart doc --output=/tmp/docs

  - uses: actions/upload-artifact@v4
    with:
      name: docs
      path: /tmp/docs
