name: Documentation generation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart doc
      - run: ls .

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: path/to/artifact/

